project:
  type: website

website:
  title: "pollutionOcc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, custom.css]
    code-fold: true
jupyter: python3

editor: visual

